name: Code verification trigger when a pull request is made

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Install az ml extension
      run: echo "Will add code check here in next challenge"
