name: Manually deploy an MLFLow model

on: 
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Check where my directory
      run:  pwd
    - name: Set up a default resource group
      run:  az configure --defaults group="diabetes-dev-rg"
    - name: Set default workspace
      run:  az configure --defaults workspace="aml-diabetes-dev"
    - name: Get the model from the last run
      run:  JOB_NAME=$(az ml job list --query "[0].name" | tr -d '"')
    - name: Register the model 
      run:  az ml model create --name "$JOB_NAME-diabetes-model" --type "mlflow_model" --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"
    - name: Create endpoint yaml file
      run:  |
        printf "\$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json\nname: $JOB_NAME-diabetes-endpoint\nauth_mode: key" > create-endpoint.yml
